### PR TITLE
F/fix coin api dependencies

### PR DESCRIPTION
**Pull request by ivcosla**
This fixes the dependencies so the [server at coin-api] (https://github.com/skycoin/services/tree/master/coin-api/cmd/coin-api) can compile.

### CODE REVIEW

**Comment by gz-c** [comment]
I don't know what the status of travis for all project in this repository is.  They will need to be fixed.

**Comment by nutmix** [comment]
@gz-c  

There are many separate and unrelated projects and libraries in services repo. Neither Travis nor github is designed to work in this way.  There are two potential solutions to creating a builds scripts:

1. always build all projects in services, every time code is committed.  This is not ideal.  Errors in one project will affect all projects, and there is likely to be a build backlog.
2. Write a script to traverse each project (sub dir) in services, looking for which one has changes, and only build that one.   

In either case, we would probably need to do the build steps in scripts outside of travis, as travis can only have one of each build directive, and only in the defined order.  Putting many projects into one travis.xml would be unmaintainable.

The proper solution is to have each project in its own repo, but this is not an option.

**Comment by gz-c** [comment]
>always build all projects in services, every time code is committed. This is not ideal. Errors in one project will affect all projects, and there is likely to be a build backlog.

The only problem here is that it may be slow.  Errors introduced in one project shouldn't be merged if the tests do not pass.

We can move mature projects out to their own repo as well

**Comment by skycoin-manager** [comment]
force merge; will move out later

**Pull request merged**
