### PR TITLE
First working version of tools to deploy new coin is ready

### PR DESCRIPTION
**Pull request by mihis**

### CODE REVIEW

**Comment by skycoin-manager** [comment]
This has command line parameters for starting a master node and starting slave nodes?

**Comment by gz-c** [comment]
@skycoin-manager @iketheadore needed to review this before merging

**Comment by skycoin-manager** [comment]
Yes. but is not critical. We will see if it works.

**Comment by mihis** [comment]
@skycoin-manager An option to start node in master/slave mode exist. However few things are missing. As far as I understand, when master node for new coin is started, it is the only trusted peer of new network, so `daemon.NewDaemon` is run without default connections. When I start slave node, it should know about master's address, so it must be provided as command line parameter. And all slave nodes must start on ports, different from master, so command line parameters to override port from config file is neccessary. Is this right?

**Comment by skycoin-manager** [comment]
That is incorrect.
- start all nodes with the default connections
- the master node should connect out to the default connections
- no one can connect to the master node because its behind a firewall
- if you are running the slave nodes on same box as the other nodes, yes they all need different ports, yes it is needed
- please set the default port to a different port than skycoin

**Comment by olemis** [comment]
@mihis , at least for Skycoin nodes there is no need for yet another command line parameter for loading default connections from file . We planned to go that way initially when we developed a candidate `testnet` for Skycoin in [olemis_t828_skycoin_testnet branch @ simelo/skycoin](https://github.com/simelo/skycoin/tree/olemis_t828_skycoin_testnet) . We switched to other path . This is what we did.

The code in former `testnet` branch already implemented a `-testchain` parameter. Once this option is enabled node configuration will look for a file in `$DATADIR/connections.txt` . It is considered a list of `IPaddress:port` pairs to establish peer connections and overrides `DefaultConnections`. For testnet `DATADIR` defaults to `~/.skycoin-testnet` but this value may be customized via (already existing) `-data-dir` cli option .

There is also [olemis_t828_skycoin_docker_testnet branch @ simelo/skycoin](https://github.com/simelo/skycoin/tree/olemis_t828_skycoin_docker_testnet) implementing some deployment scripts with Docker for testing purposes (... still work in progress) .

Regarding @skycoin-manager comment , the combination of both branches works as follows:

- all nodes are started with the default connections (including the master node)
- the master node connects out to the default connections
- all nodes can connect to the master node , no firewall
  * p.s. if no connection may be established to master node how is synchronization meant to happen ?
- all nodes are containers connected to a virtual (Docker) network interface
- port and configuration info is documented [here](https://github.com/skycoin/docs/blob/master/docs/skycoin/_data/devdocs/en/references/p2p_networking.md#constants-and-defaults) and are applied to each container since they are isolated.
- a testnet.go script launches the whole network via (generated) docker-compose 
- aforementioned script configures container nodes and creates a single `connections.txt` mounted in all containers via a Docker volumes 

I mention this because there is a chance for what we've done to be of some help for the work made in this ticket . Besides maybe both lines of development should converge somehow , and we would be open to adapt considering your feedback , if any .

**Q**: @stdevMauricio is it possible to add some routing info to the Docker virtual network iptables so that the very same deployment can be used to connect them containers to another (virtual, software defined, ...) network ?

Cc @stdevMauricio @stdevEdu @stdevStark @gz-c

**Comment by olemis** [comment]
p.s. after reviewing testnet code I noticed that `--port` was removed in [olemis_t828_skycoin_testnet branch @ simelo/skycoin](https://github.com/simelo/skycoin/tree/olemis_t828_skycoin_testnet) . I'll restore them back soon .

**Pull request merged**
